-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "s1_curRanking" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "s1_lossess" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "s1_prevRanking" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "s1_ranked" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "s1_score" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "s1_totalGames" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "s1_wins" INTEGER NOT NULL DEFAULT 0;